// generated by parseCompaniesCsv.js
// DO NOT EDIT MANUALLY. ONLY GENERATE USING 'npm run parse-companies'
/**** GEN:S id="companies-csv" */
export const companies = JSON.parse(`[
  {
    "companyName": "Trio Animation ",
    "focuses": "Animation, Agentic AI Visual Configurators for Industrial and Manufacturing Verticals",
    "positionTypes": [
      "Interns",
      "Full-time employees"
    ],
    "website": "https://www.trioanimation.com",
    "virtualTimes": "",
    "inPersonTimes": "10:30 - 11:00, 11:00 - 11:30, 11:30 - 12:00, 12:30 - 1:00, 1:00 - 1:30",
    "logoUrlCheckString": "Option 2 Logo emailed. "
  },
  {
    "companyName": "RWS Global",
    "focuses": "Graphic Design, Experiential Design for theme parks, museums, zoos, brand attractions",
    "positionTypes": [
      "Interns",
      "Contract workers",
      "Freelancers"
    ],
    "website": "https://www.rwsglobal.com",
    "virtualTimes": "10:00 - 10:30, 10:30 - 11:00",
    "inPersonTimes": "",
    "logoUrlCheckString": "Option 2"
  },
  {
    "companyName": "Imagine Advertising Studio",
    "focuses": "Graphic Design, Large format digital printing ",
    "positionTypes": [
      "Interns",
      "Part-time employees",
      "Contract workers",
      "Freelancers"
    ],
    "website": "imagineadvertisingstudio.com",
    "virtualTimes": "All Day",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://drive.google.com/file/d/1uN3q9WziZWrBfAt5c3wwttCI8vgDRxxB/view?usp=sharing"
  },
  {
    "companyName": "Electronic Arts, EA SPORTS",
    "focuses": "Animation, Game Development, Graphic Design, Virtual Production",
    "positionTypes": [
      "Interns",
      "Full-time employees"
    ],
    "website": "www.ea.com",
    "virtualTimes": "10:00 - 10:30, 12:30 - 1:00",
    "inPersonTimes": "",
    "logoUrlCheckString": "option 2"
  },
  {
    "companyName": "Texas Film Commission",
    "focuses": "State government organization that assists with all these industries",
    "positionTypes": [
      "Interns",
      "Members"
    ],
    "website": "https://gov.texas.gov/film",
    "virtualTimes": "",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "Option 2"
  },
  {
    "companyName": "Cloud 10 Studios",
    "focuses": "Animation",
    "positionTypes": [
      "Interns",
      "Part-time employees",
      "Contract workers",
      "Freelancers"
    ],
    "website": "www.cloud10studios.com",
    "virtualTimes": "10:00 - 10:30, 10:30 - 11:00, 11:00 - 11:30, 11:30 - 12:00",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "Option 2"
  },
  {
    "companyName": "Audience Media Group",
    "focuses": "Graphic Design",
    "positionTypes": [
      "Full-time employees",
      "Part-time employees"
    ],
    "website": "https://www.ataudience.com/",
    "virtualTimes": "All Day",
    "inPersonTimes": "All Day",
    "logoUrlCheckString": "https://drive.google.com/file/d/1c9WT5YoshroV2ohTJhOrzxzGEp41ehw7/view?usp=sharing"
  }
]`);
/**** GEN:E id="companies-csv" */

// edit manually
export const pastCompanies: string[] = Array.from(new Set([
  "900lbs",
  "A Bunch Of Short Guys",
  "AEM Creations",
  "Aggieland Outfitters",
  "Bluepoint Games",
  "BonusXP",
  "Booz Allen Hamilton, Inc.",
  "C.C. Creations",
  "Cinevva",
  "Click Here Labs - TRG",
  "Cloud Imperium Games",
  "Credera",
  "Deloitte",
  "Digital Seat Media",
  "DreamWorks Animation",
  "Electronic Arts",
  "Framestore",
  "Game Worlds",
  "Gearbox Software",
  "IMG Studio",
  "Jacobs Architects",
  "Mighty Coconut",
  "Pixar",
  "Powerhouse Animation",
  "ReelFX",
  "Six Foot Games",
  "Texas Film Commission",
  "Texas Moving Picture Alliance (TXMPA)",
  "The Third Floor, Inc.",
  "TRG",
  "Walt Disney",
  "Viasat",
]));
pastCompanies.sort((a, b) => a.toLowerCase() <= b.toLowerCase() ? -1 : 1);
